# Generated by Django 4.1.4 on 2022-12-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_fisico_link_de_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='digital',
            name='slug',
            field=models.SlugField(default='titulo', max_length=400, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fisico',
            name='slug',
            field=models.SlugField(default='titulo', max_length=400, unique=True),
            preserve_default=False,
        ),
    ]
