# Generated by Django 4.1.4 on 2022-12-25 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0007_fisico_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='digital',
            name='users_likes',
            field=models.ManyToManyField(blank=True, related_name='digital_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fisico',
            name='users_likes',
            field=models.ManyToManyField(blank=True, related_name='fisico_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
