# Generated by Django 4.1.4 on 2022-12-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_digital_users_likes_fisico_users_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='digital',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fisico',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
