# Generated by Django 4.1.4 on 2022-12-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_comentario_f_comentario_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario_d',
            name='revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario_f',
            name='revision',
            field=models.BooleanField(default=False),
        ),
    ]
